name: Multi-Arch Caddy Image Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
          - platform: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver: docker-container

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .  # Assuming the Dockerfile is in the root of the repository
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: ghcr.io/skyblaster/caddy:latest  # Use a single tag for both architectures

  create-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Manifest
        run: |
          echo "Creating manifest for ghcr.io/skyblaster/caddy:latest"
          docker manifest create ghcr.io/skyblaster/caddy:latest \
            --amend ghcr.io/skyblaster/caddy:${{ needs.build-and-push.outputs.TAG_amd64 }} \
            --amend ghcr.io/skyblaster/caddy:${{ needs.build-and-push.outputs.TAG_arm64 }}
          docker manifest push ghcr.io/skyblaster/caddy:latest